debug: true
map_frame: map
odom_frame: map
base_frame: base_footprint

dock:
  dock_speed: 0.05
  dock_distance: 1.0
  pose_x: 20.8905636619
  pose_y: 14.6787757997
  pose_z: 0.0
  orientation_x: 0.0
  orientation_y: 0.0
  orientation_z: -0.0289632634423 
  orientation_w: 0.999580476685
