subscribers:
  - name:        "Safety controller"
    topic:       "input/safety_cmd"
    timeout:     0.5
    priority:    0
    short_desc:  "Safety controller"
  - name:        "Joy"
    topic:       "input/joy_cmd"
    timeout:     0.1
    priority:    1
    short_desc:  "Joystick controller"
  - name:        "Navigation stack"
    topic:       "input/navigation_cmd"
    timeout:     0.5
    priority:    2
    short_desc:  "Navigation stack controller"
publisher:       "output/cmd_vel"